In [100]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [148]:
# Open the Movies_EDA.csv file from the data folder
movies = pd.read_csv('../data/Movies_EDA.csv')
movies.head()

,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary,Net Profit,ROI
0,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on...",288500000.0,38.466667
1,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...,138293296.0,18.439106
2,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b...",58079915.0,4.467686
3,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...,147001698.0,10.500121
4,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret...",69431625.0,4.628775

In [149]:
# drop the summary and title columns
movies = movies.drop(columns=['Summary', 'Title'])

In [150]:
# Change 'Release Date' to only have the month (1-12)

movies['Release Date'] = pd.to_datetime(movies['Release Date']).dt.month

In [151]:
movies.head()

,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Net Profit,ROI
0,PG-13,7500000.0,296000000.0,10,Romance,93.0,5.9,73638.0,288500000.0,38.466667
1,PG,7500000.0,145793296.0,12,Comedy,99.0,7.4,91075.0,138293296.0,18.439106
2,PG,13000000.0,71079915.0,7,Crime,100.0,7.2,91415.0,58079915.0,4.467686
3,R,14000000.0,161001698.0,12,War,145.0,7.2,91415.0,147001698.0,10.500121
4,PG,15000000.0,84431625.0,4,Drama,107.0,7.5,101702.0,69431625.0,4.628775

In [152]:
# Create dummy variables for 'MPAA Rating' and 'Genre'
movies_dummies = pd.get_dummies(movies, columns=['MPAA Rating', 'Genre'],dtype='int', drop_first=False)

In [153]:
movies_dummies.head()

,Budget,Gross,Release Date,Runtime,Rating,Rating Count,Net Profit,ROI,MPAA Rating_G,MPAA Rating_PG,...,Genre_Family,Genre_Fantasy,Genre_History,Genre_Horror,Genre_Mystery,Genre_Romance,Genre_Science Fiction,Genre_Thriller,Genre_War,Genre_Western
0,7500000.0,296000000.0,10,93.0,5.9,73638.0,288500000.0,38.466667,0,0,...,0,0,0,0,0,1,0,0,0,0
1,7500000.0,145793296.0,12,99.0,7.4,91075.0,138293296.0,18.439106,0,1,...,0,0,0,0,0,0,0,0,0,0
2,13000000.0,71079915.0,7,100.0,7.2,91415.0,58079915.0,4.467686,0,1,...,0,0,0,0,0,0,0,0,0,0
3,14000000.0,161001698.0,12,145.0,7.2,91415.0,147001698.0,10.500121,0,0,...,0,0,0,0,0,0,0,0,1,0
4,15000000.0,84431625.0,4,107.0,7.5,101702.0,69431625.0,4.628775,0,1,...,0,0,0,0,0,0,0,0,0,0

In [155]:
#Scaling numerical columns but not gross, ROI, or Net Profit becasue it is the target variable
# and we do not want to scale the target variable.
# Columns to scale
scale_cols = ['Budget', 'Runtime', 'Rating', 'Rating Count']

# Initialize scaler and fit_transform
scaler = StandardScaler()
movies_dummies = movies_dummies.copy()
movies_dummies[scale_cols] = scaler.fit_transform(movies_dummies[scale_cols])

In [156]:
movies_dummies.head()

,Budget,Gross,Release Date,Runtime,Rating,Rating Count,Net Profit,ROI,MPAA Rating_G,MPAA Rating_PG,...,Genre_Family,Genre_Fantasy,Genre_History,Genre_Horror,Genre_Mystery,Genre_Romance,Genre_Science Fiction,Genre_Thriller,Genre_War,Genre_Western
0,-1.284438,296000000.0,10,-1.100607,-1.146270,-0.831512,288500000.0,38.466667,0,0,...,0,0,0,0,0,1,0,0,0,0
1,-1.284438,145793296.0,12,-0.832114,0.549913,-0.776143,138293296.0,18.439106,0,1,...,0,0,0,0,0,0,0,0,0,0
2,-1.191530,71079915.0,7,-0.787365,0.323756,-0.775063,58079915.0,4.467686,0,1,...,0,0,0,0,0,0,0,0,0,0
3,-1.174637,161001698.0,12,1.226329,0.323756,-0.775063,147001698.0,10.500121,0,0,...,0,0,0,0,0,0,0,0,1,0
4,-1.157745,84431625.0,4,-0.474124,0.662992,-0.742398,69431625.0,4.628775,0,1,...,0,0,0,0,0,0,0,0,0,0

In [157]:

movies_dummies.shape

(504, 28)

In [158]:
# Spliting the dataset into training and testing sets
# Predicting 'Net Profit' as the target variable
X = movies_dummies.drop('Net Profit', axis=1)
y = movies_dummies['Net Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [159]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((378, 27), (126, 27), (378,), (126,))

In [ ]:
#saving the processed data to a new CSV file
movies_dummies.to_csv('../data/movies_scaled_dummies.csv', index=False)

In [161]:
import joblib

# Save the fitted scaler to an external file
joblib.dump(scaler, '../data/standard_scaler.pkl')

['../data/standard_scaler.pkl']