In [17]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [18]:
# Open the Movies_EDA.csv file from the data folder
movies = pd.read_csv('../data/Movies_EDA.csv')
movies.head()

,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary,Net Profit,ROI
0,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on...",288500000.0,38.466667
1,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...,138293296.0,18.439106
2,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b...",58079915.0,4.467686
3,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...,147001698.0,10.500121
4,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret...",69431625.0,4.628775

In [19]:
# Create dummy variables for 'MPAA Rating' and 'Genre'
movies_dummies = pd.get_dummies(movies, columns=['MPAA Rating', 'Genre'],dtype='int', drop_first=False)

In [20]:

movies_dummies.head()

,Title,Budget,Gross,Release Date,Runtime,Rating,Rating Count,Summary,Net Profit,ROI,...,Genre_Family,Genre_Fantasy,Genre_History,Genre_Horror,Genre_Mystery,Genre_Romance,Genre_Science Fiction,Genre_Thriller,Genre_War,Genre_Western
0,Look Who's Talking,7500000.0,296000000.0,1989-10-12,93.0,5.9,73638.0,"After a single, career-minded woman is left on...",288500000.0,38.466667,...,0,0,0,0,0,1,0,0,0,0
1,Driving Miss Daisy,7500000.0,145793296.0,1989-12-13,99.0,7.4,91075.0,An old Jewish woman and her African-American c...,138293296.0,18.439106,...,0,0,0,0,0,0,0,0,0,0
2,Turner & Hooch,13000000.0,71079915.0,1989-07-28,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b...",58079915.0,4.467686,...,0,0,0,0,0,0,0,0,0,0
3,Born on the Fourth of July,14000000.0,161001698.0,1989-12-20,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...,147001698.0,10.500121,...,0,0,0,0,0,0,0,0,1,0
4,Field of Dreams,15000000.0,84431625.0,1989-04-21,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret...",69431625.0,4.628775,...,0,0,0,0,0,0,0,0,0,0

In [21]:


#Scaling numerical columns
# Columns to scale
scale_cols = ['Budget', 'Gross', 'Runtime', 'Rating', 'Rating Count', 'Net Profit', 'ROI']

# Initialize scaler and fit_transform
scaler = StandardScaler()
movies_scaled = movies.copy()
movies_scaled[scale_cols] = scaler.fit_transform(movies[scale_cols])

In [22]:
movies_scaled.head()

,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary,Net Profit,ROI
0,Look Who's Talking,PG-13,-1.278652,-0.310708,1989-10-12,Romance,-1.091698,-1.150182,-0.833950,"After a single, career-minded woman is left on...",-0.040434,5.851701
1,Driving Miss Daisy,PG,-1.278652,-0.852047,1989-12-13,Comedy,-0.827165,0.547302,-0.778939,An old Jewish woman and her African-American c...,-0.659631,2.338609
2,Turner & Hooch,PG,-1.186607,-1.121311,1989-07-28,Crime,-0.783077,0.320971,-0.777866,"Det. Scott Turner (Tom Hanks) is an uptight, b...",-0.990294,-0.112158
3,Born on the Fourth of July,R,-1.169872,-0.797236,1989-12-20,War,1.200920,0.320971,-0.777866,The biography of Ron Kovic. Paralyzed in the V...,-0.623732,0.946009
4,Field of Dreams,PG,-1.153137,-1.073192,1989-04-21,Drama,-0.474455,0.660468,-0.745412,"An Iowa corn farmer, hearing voices, interpret...",-0.943499,-0.083901

In [23]:
# Spliting the dataset into training and testing sets
# Predicting 'Net Profit' as the target variable
X = movies_scaled.drop('Net Profit', axis=1)
y = movies_scaled['Net Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [24]:
movies_scaled.to_csv('../data/movies_scaled_dummies.csv', index=False)